### ISSUE TITLE
Not able  to run this application

### ISSUE THREAD

**Issue by atuljain** [mcknightg/flutterbum#17]
Hi 
i am new bie to learn meteor and 
i am not able to successfully run this app 
i am getting this error , please let me know how to et rid out from here 

W20150226-12:35:52.923(5.5)? (STDERR)  
W20150226-12:35:52.924(5.5)? (STDERR) /sysusers/atul/.meteor/packages/meteor-tool/.1.0.40.1ef5dzv++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:173
W20150226-12:35:52.924(5.5)? (STDERR)                       throw(ex);
W20150226-12:35:52.924(5.5)? (STDERR)                             ^
W20150226-12:35:52.926(5.5)? (STDERR) TypeError: Object [object Object] has no method 'helpers'
W20150226-12:35:52.926(5.5)? (STDERR)     at app/collections/items.js:3:7
W20150226-12:35:52.926(5.5)? (STDERR)     at app/collections/items.js:11:3
W20150226-12:35:52.927(5.5)? (STDERR)     at /sysusers/atul/flutterbum/.meteor/local/build/programs/server/boot.js:205:10
W20150226-12:35:52.927(5.5)? (STDERR)     at Array.forEach (native)
W20150226-12:35:52.927(5.5)? (STDERR)     at Function._.each._.forEach (/sysusers/atul/.meteor/packages/meteor-tool/.1.0.40.1ef5dzv++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20150226-12:35:52.927(5.5)? (STDERR)     at /sysusers/atul/flutterbum/.meteor/local/build/programs/server/boot.js:116:5
=> Exited with code: 8
=> Your application is crashing. Waiting for file change.

**Comment by atuljain** [comment]
after installing fibres , i got another error message 

   While building the application:
   node_modules/fibers/build.js:1:15: Unexpected token ILLEGAL
   node_modules/fibers/test.js:1:15: Unexpected token ILLEGAL

please let me know solution for this
